# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93acebad4cdef3c355ff6ceea4909e05fea826f00749076ecd4dbf2dadf9d6aef19bf2f04b91ae4f71481e10041fe127324a3a3d004d7a99890451928e09248

test:
  secret_key_base: 04d6646cc004d35ca16f53feb5fcc5865ba2a0323b9c5a1bcc1684ac15daa49b18e91ad1ccc3c6bbe6da4d439b5adc60c9199e19629f29889ad5871bf14050d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
